@startuml
title Процесс работы администратора приюта

|Администратор|
start
:Вход в админ-панель;

partition "Управление животными" {
  :Добавление нового животного;
  :Редактирование данных;
  :Изменение статуса животного;
  :Внесение данных о прививках;
  :Внесение истории болезней;
  :Отметка о стерилизации;
}
partition "Управление медицинскими данными" {
  :Внесение данных о прививках;
  :Внесение истории болезней;
  :Отметка о стерилизации;
}
partition "Управление событиями" {
  :Просмотр событий;
  :Добавление событий;
}

partition "Обработка заявок" {
  :Просмотр новой заявки от пользователя;
  
  if (Решение по заявке) then (Одобрено)
    :Смена статуса на "Одобрено";
    :Смена статуса животного на "Забронировано";
    
    if (Животное усыновлено?) then (да)
      :Смена статуса животного на "Усыновлено";
    else (нет)
    endif
    
  else (Отказ)
    :Смена статуса на "Отказ" с указанием причины;
  endif
}

stop
:Конец процесса;
@enduml