@startuml
title Процесс усыновления животного

|Пользователь|
start
:Вход на сайт;
:Просмотр каталога животных;

|Система|
if (Поиск с фильтром?) then (да)
  :Применение фильтров;
else (нет)
endif

|Пользователь|
:Выбор животного из списка;
:Просмотр развернутой карточки\\животного;
:Решение;

if (Забрать животное?) then (да)
  :Заполнение заявки;
  :Отправка заявки;
  
  |Система|
  :Рассматривается;
  
  |Пользователь|
  :Отслеживание статуса заявки;
  
  |Система|
  if (Проверка статуса) then (Одобрено)
    :Уведомления о согласии\\и дальнейших шагах;
  else (Отказ)
    :Уведомление с причиной отказа;
  endif
  
  |Пользователь|
else (нет)
endif

stop

@enduml